ERR_JSONParseError = 'Error parsing JSON.'
ERR_Non200Resp = 'Non-OK (%(response)s) response received when authenticating.'
ERR_InvalidResp = 'We recieved an invalid response when trying to log you in. If the problem persists, please contact Toontown Rewritten Support.'
ERR_InvalidLogin = 'Looks like you have an invalid username and/or password. Try again!'
ERR_TFAWithoutToken = 'Cannot input Two-Step Login code while there is no token!'
ERR_AccServerDown = "We're having a hard time contacting the Account Server. Try again soon!"
ERR_DelayWithoutToken = 'Attempted to delay login without a queue token!'
ERR_UnknownTraceback = 'Encountered a fatal error. Details saved to crash.txt'
UnableToCheckForUpdates = 'Unable to check for Launcher Updates'
LauncherUpdateHeader = 'Launcher Update!'
LauncherUpdateAvailabile = "Hey, your Toontown Rewritten Launcher needs an update!\n\nNew Version %s:\n%s\n\nClick 'OK' below and we'll send you off to get the new version!"
GUI_Authing = 'Contacting the Toon Council...'
GUI_Queue = "Inserting you into the Tooniverse... (You'll be in-game in around %ss.)"
GUI_TFA = 'Two-Step Login'
GUI_TFAWhatsThis = "You've enabled Two-Step Login for your account! Enter your login code from the app registered to your account to get into Toontown. If you need help, contact Toontown Rewritten Support."
GUI_Error = 'Yipes!'
GUI_VersionLabel = 'Toontown Launcher v%s'
GUI_WindowTitle = 'Toontown Rewritten'
GUI_PlayGameFarewell = 'Have Fun!'
GUI_CrashedTitle = 'Gadzooks!'
GUI_CrashedQuestion = 'Looks like Toontown Rewritten crashed. Make sure to check your log file and report it for fixing! Would you like to try logging in again?'
GUI_PlayAgain = 'Hope you had fun in Toontown. Come back soon!'
