LAUNCHER_ERROR = 0
LAUNCHER_VERSION_UPDATE = 1
LAUNCHER_REQUEST_TFA = 2
LAUNCHER_STATUS = 3
LAUNCHER_PROGRESS = 4
LAUNCHER_PLAY_RETRY = 5
LAUNCHER_ENABLE_CONTROLS = 6
LAUNCHER_CLEAR_PASSWORD = 7
LAUNCHER_HIDE = 997
LAUNCHER_SHOW = 998
LAUNCHER_EXIT = 999

